---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-gitops-repo-001
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-gitops-repo-001
  url: ssh://git@github.com/jamwils/gitops-repo-001.git

